name: Publish WhatsApp Integration

on:
  push:
    tags:
      - 'v*'
  pull_request:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: install
        run: |
          git config --global url."https://${{ secrets.PAT_USER }}:${{ secrets.PAT }}@github.com/".insteadOf "https://github.com/"

      - uses: oven-sh/setup-bun@v1

      - uses: TextsHQ/platform-integration-builder@v2.5.12
        name: "Publish WhatsApp Integration"
        id: publishWhatsApp
        with:
          s3-access-key-id: ${{ secrets.S3_ACCESS_KEY_ID }}
          s3-access-key: ${{ secrets.S3_ACCESS_KEY }}
          s3-endpoint: https://uploads.texts.com
          prebuild: |
            yarn build

      - uses: thollander/actions-comment-pull-request@v2
        if: github.event_name == 'pull_request'
        with:
          comment_tag: manifest-whatsapp
          message: ${{ steps.publishWhatsApp.outputs.summary }}

      - name: Results (WhatsApp)
        run: |
          echo "${{ steps.publishWhatsApp.outputs.summary }}"
